apiVersion: kustomlze.config.k8s.io/v1beta1
kind: Kustomlzation
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
namespace: ml
images:
- name: ml-image
  newName: mazcot4devops/ml-app
  newTag: latest
