apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ml-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
