apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-app
  namespace: ml
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/mazcot-devops/project-test'
    path: 'charts/templates'
    targetRevision: 'master'
  project: ml-life
  syncPolicy:
    automated: {}
